name: dotnet

on:
  push:
    branches: [ "master", "Setup_CD-CI" ]
  pull_request:
    branches: [ "master", "Setup_CD-CI" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      dotnet-version: '7.0.x'

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet ${{ dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ dotnet-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  call-docker:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [build]
    uses: ./.github/workflows/docker.yml